[package]
name = "hex_str"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1"
rand = { version = "0.8.4", optional = true, features = ["min_const_gen"] }
serde = { version = "1", features = ["derive"], optional = true }
thiserror = "1"

[features]
serde = ["dep:serde"]
rand = ["dep:rand"]
